name: Release semantic-release
on:
  workflow_dispatch:
    branches:
      - "testing_ci"
    inputs:
      releaseType:
        description: "Type of release (major, minor, patch)"
        required: true
        default: "patch"
jobs:
  # release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 20
  #     - run: npm install --frozen-lockfile
  #     - run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Run Semantic Release
        run: |
          npx semantic-release --release-as ${{ github.event.inputs.releaseType }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
